### PR TITLE
[Backend] User model

### PR DESCRIPTION
**Pull request by deploy-soon**
### Build Server
```bash
python manage.py makemigrations
python manage.py migrate
python manage.py runserver
```
### Request form
```
$ curl -X post -H "Authorization: JWT <your_token>" http://localhost:8000/api/user/1

```

### CODE REVIEW

**Comment by deploy-soon** [comment]
Result of TestCase

- test code : [`1621fa`](https://github.com/swsnu/swpp2019-team6/commit/1621fab4bdebc79e2a029563af9334019a031d26)

- run the test
```
$ coverage run --source='.' manage.py test user
$ coverage report
```

- result of test cases
```
Name                                          Stmts   Miss  Cover
-----------------------------------------------------------------
manage.py                                        12      2    83%
triplannet/__init__.py                            0      0   100%
triplannet/settings.py                           22      0   100%
triplannet/urls.py                                3      0   100%
triplannet/wsgi.py                                4      4     0%
user/__init__.py                                  0      0   100%
user/admin.py                                     1      0   100%
user/apps.py                                      3      0   100%
user/migrations/0001_initial.py                   5      0   100%
user/migrations/0002_auto_20191020_0616.py        4      0   100%
user/migrations/0003_auto_20191020_0640.py        5      0   100%
user/migrations/0004_user_status_message.py       4      0   100%
user/migrations/__init__.py                       0      0   100%
user/models.py                                   12      1    92%
user/serializers.py                              46     10    78%
user/tests.py                                    67      2    97%
user/urls.py                                      4      0   100%
user/views.py                                    52      1    98%
-----------------------------------------------------------------
TOTAL                                           244     20    92%
```

**Comment by jangdonghae** [comment]
nice job!

**Comment by deploy-soon** [comment]
The examples of API usage are added on [issue](https://github.com/swsnu/swpp2019-team6/issues/12#issuecomment-544798944).

**Comment by RXWE** [comment]
login부분 다 작업하셨으면 merge해 주셔도 될 것 같아요!

**Comment by deploy-soon** [comment]
Login response has changed.
Response format is [here](https://github.com/swsnu/swpp2019-team6/issues/12#issuecomment-546193919) .

**Pull request merged**
